import instrumentStore
from instrumentStore import *

shop = instrumentStore.insturmentStore()

g1 = Guitar("electric", "Yamaha", 1234)
g2 = Guitar("acoustic", "Fender", 2500)
g3 = Guitar("classic", "Gibson", 5000)
g4 = Guitar("electric", "Ibanez", 1800)
g5 = Guitar("acoustic", "Taylor", 3000)
g6 = Guitar("classic", "Martin", 4000)

p1 = Piano("3-octaves", "Yamaha", 5000)
p2 = Piano("5-octaves", "Kawai", 8000)
p3 = Piano("7-octaves", "Steinway & Sons", 12000)
p4 = Piano("3-octaves", "Roland", 4000)
p5 = Piano("5-octaves", "Casio", 3000)
p6 = Piano("7-octaves", "Bösendorfer", 15000)

d1 = Drums("7-piece", "Pearl", 1500)
d2 = Drums("9-piece", "Tama", 2000)
d3 = Drums("11-piece", "Ludwig", 2500)
d4 = Drums("7-piece", "DW", 1800)
d5 = Drums("9-piece", "Mapex", 1600)
d6 = Drums("11-piece", "Gretsch", 2200)

shop.add_new_instrument(g1)
shop.add_new_instrument(g2)
shop.add_new_instrument(g3)
shop.add_new_instrument(g4)
shop.add_new_instrument(g5)
shop.add_new_instrument(g6)
shop.add_new_instrument(p1)
shop.add_new_instrument(p2)
shop.add_new_instrument(p3)
shop.add_new_instrument(p4)
shop.add_new_instrument(p5)
shop.add_new_instrument(p6)
shop.add_new_instrument(d1)
shop.add_new_instrument(d2)
shop.add_new_instrument(d3)
shop.add_new_instrument(d4)
shop.add_new_instrument(d5)
shop.add_new_instrument(d6)

shop.show_insruments()
